### ISSUE TITLE
Config: Make non-required config Optional

### ISSUE THREAD

**Issue by rutiolma** [openfed/kiso#1]
We don't always have a "Search" functionality so we shouldn't depend on module "search" as is the case for https://github.com/openfed/kiso/blob/master/config/install/block.block.kiso_searchform.yml

The solution may be to create an "optional" folder for this configuration (and maybe others?!) so it will be relocated to ./config/**optional**/block.block.kiso_searchform.yml

For more info: https://www.drupal.org/node/2453919

**Comment by smillart** [comment]
We do not really need the search form block. I just removed it from the default install configuration. This will be available in the next release (v1.2-dev)
