### ISSUE TITLE
URL for noscript element only works without raw filter.

### ISSUE THREAD

**Issue by piofernandes** [openfed/kiso#16]
https://github.com/openfed/kiso/blob/8cb9f47333e2e0bcec2e56a8401c062a64ea1a3a/templates/layout/html.html.twig#L55

It seems that on my subtheme, the url is only outputted if I remove the |raw

**Comment by smillart** [comment]
To work properly, the following source string should be available for translation [ `admin/config/regional/translate` ] as default (English) language:

```
For full functionality of this site it is necessary to enable JavaScript.<br> Here are the <a href="@enable_js_url" target="_blank"> instructions how to enable JavaScript in your web browser</a>.
```

I think... This is not your case...
