### ISSUE TITLE
Empty region detection fails with trailing whitespace

### ISSUE THREAD

**Issue by michael-acampora** [openfed/kiso#23]
https://github.com/openfed/kiso/blob/c78d26825c461b35ad59228987b2a600748af81f/includes/preprocess.page.inc#L12-L19

There can be trailing white space when rendering the region in kiso_preprocess_page.
This can be fixed by adding a trim around strip_tags.

**Comment by smillart** [comment]
Thanks @michael-acampora for reporting this issue, I will take care of it...

**Comment by smillart** [comment]
@michael-acampora, I created the "**Pull request #26**" which contains the fix to ensure removing trailing whitespace for empty region detection. Could you please review and let me know if this is what you expected. Thanks!

**Comment by michael-acampora** [comment]
Looks good, before the output was " \n", now it's "".

**Comment by smillart** [comment]
This bug fix will be available with the next **release 2.6**.
