### ISSUE TITLE
Empty region detection fails for placeholders

### ISSUE THREAD

**Issue by rutiolma** [openfed/kiso#31]
https://github.com/openfed/kiso/blob/71ff72cad96b8a3da37ed2cd9082220a46eb32d8/includes/preprocess.page.inc#L18

We need a better check to see if the block is empty. For example if the content is a "`<drupal-render-placeholder>`" or an "`<img>`" the current check will fail. 
It would be nice if strip_tags could allow some tags.

This is a problem, for example, with Indexed Views exposed forms assigned to a region.

**Comment by smillart** [comment]
Thanks @rutiolma for reporting this issue.
I'm afraid to not be able to make the difference between "" and ""... Any idea?

**Comment by rutiolma** [comment]
Comment updated, HTML was stripped :)

**Comment by smillart** [comment]
This bug fix will be available with the next **release 2.7**.

**Comment by rutiolma** [comment]
This fix has some regressions.
Also, if a region is empty, there's a fatal error.
