### ISSUE TITLE
Include the Outdated Browser v1.1.5

### ISSUE THREAD

**Issue by rutiolma** [openfed/kiso#5]
An outdated Browser message should be included.
Same as: https://github.com/openfed/openfed8/issues/41

**Comment by smillart** [comment]
The **_Drupal Kiso (基礎)_** base theme should implement the [**Outdated Browser v1.1.5**](https://github.com/outdatedbrowser/outdated-browser), a time saving tool for developers.

With this solution it will be able to check if the user’s _Microsoft_ browser can handle your website. If not, it will show a notice advising the user to update his browser for latest versions. It will be up to the user to upgrade... or not.

**Comment by smillart** [comment]
This enhancement will be available with the next **release 2.6**.
