### ISSUE TITLE
JS issue with extlink-window.js

### ISSUE THREAD

**Issue by laurent-b4y** [openfed/kiso#54]
I get this in the console log when using the extlinkwindow.js option from the theme.

```
drupal.js?v=8.9.20:13 Uncaught TypeError: Cannot read properties of null (reading 'textContent')
    at i.setAttributeValues (extlink-window.min.js?v=8.9.20:1:4037)
    at i.init (extlink-window.min.js?v=8.9.20:1:3490)
    at Object.attach (extlink-window.min.js?v=8.9.20:1:5802)
    at drupal.js?v=8.9.20:25:24
    at Array.forEach (<anonymous>)
    at Object.Drupal.attachBehaviors (drupal.js?v=8.9.20:22:34)
    at drupal.init.js?v=8.9.20:28:12
    at HTMLDocument.listener (drupal.init.js?v=8.9.20:20:9)
```
This is the line where the error occurs 
`this.ariaLabel = (this.isSvgImage) ? this.iconElement.getAttribute('aria-label') : this.iconElement.querySelector('span.visually-hidden').textContent;`

As far as I can tell the issue only occurs when the
External Links [Settings](http://capac.lndo.site/en/admin/config/user-interface/extlink) are set to use Fontawesome icons.

Further research gave me this as the source of the issue, it's a patch that got committed to the 8.13 version of the external link module. Fixing this issue: https://www.drupal.org/project/extlink/issues/3117455

So I guess we don't need to rewrite the aria-label at all when fontawesome icons are used, I just removed line 98 in extlink-window.js.  Now I don't know if the fontawesome option is still needed on the theme level, either. Since we also have this option in the module, I find this confusing.

**Comment by rutiolma** [comment]
I'm experiencing the same issue.
