### ISSUE TITLE
Default style for file icons

### ISSUE THREAD

**Issue by rutiolma** [openfed/kiso#59]
On Openfed 7 the default theme had some default style for icons. It would be nice to have it on Kiso so we can use it in Openfed.

For example, when using append_file_info module, it adds a class to files so they can be styled according to their type. 
These classes are handled in Drupal core (see core/themes/classy/css/components/file.css) and it would be nice to have them on Kiso as well.

**Comment by smillart** [comment]
@rutiolma @jclemmenb4y @laurent-b4y I wonder one thing... May be better to use a font icons library instead of PNG images. What do you think ?

**Comment by laurent-b4y** [comment]
I agree that using a font library would be better, or some home made svg icons just to not be dependent on a potentially commercial third party.
