### ISSUE TITLE
Default style for Language Switcher block and Federal header

### ISSUE THREAD

**Issue by rutiolma** [openfed/kiso#6]
We need to activate the language switcher block by default (https://github.com/openfed/openfed8/issues/15) but right now it doesn't look nice. Can you add a default style to it?

Since language switcher is usually placed in the same region has the federal header, can you confirm if there is style for it as well?

**Comment by smillart** [comment]
Default style for "Language Switcher" and "Federal header" blocks added within the Kiso (基礎) release 2.0-dev
