### ISSUE TITLE
Check for empty regions directly in twig file for better performance

### ISSUE THREAD

**Issue by laurent-b4y** [openfed/kiso#64]
Yves brought my attention on a possible performance hit Kiso has by checking the regions content in a preprocess iso directly in twig.

We should remove the preprocess used to check the "has_navigation" and "has_complementary" and replace them with something like this in the page.html.twig file

```
{% set page_navigaton = page.navigation|render %}
{% set page_complementary = page.complementary|render %}

{% if page_navigation|striptags|trim is not empty %}
	{% set has_navigation = true %}
{% else %}
	{% set has_navigation = false %}
{% endif %}

{% if page_complementary|striptags|trim is not empty %}
	{% set has_complementary = true %}
{% else %}
	{% set has_complementary = false %}
{% endif %}
```
The rest of the file doesn't need changes AFAIK.

**Comment by GyD** [comment]
To give more detail <?php render function do not return the final output.
That could lead to false result, example: when a drupal placeholder return nothing.

This can be tested with facets and facet option that do not render facet when the facet source is not rendered.

Laurent solution is the one we put on werkenvoor but may not be the best since this issue need investigation. 

Example, with facet we currently have this output in php on page where facet are not rendered:
```html
'  <drupal-render-placeholder callback="Drupal\\block\\BlockViewBuilder::lazyBuilder" arguments="0=category&amp;1=full&amp;2" token="3H-ATSLp_IKUKYnhOjRX3yjcYQjgLT6WOepB79hscJI"></drupal-render-placeholder>
'
```
But when you render in twig it return
```html
''
```
Please note that solution implemented in Kiso also render region and their content multiples times (at least twice), that could lead to performances issues.

**Comment by smillart** [comment]
Please investigate and provide me with the best solution or better than what we have now. In that case, I will add this issue in the [**Kiso (基礎) 2.7.3**](https://github.com/openfed/kiso/milestone/7) milestone and I will implement this change request.

**Comment by smillart** [comment]
@GyD @rutiolma I'm not quite sure exactly what I'm supposed to do. Should I delete the following PHP code and only use `twig` templates to test for empty regions?

https://github.com/openfed/kiso/blob/4035ba060c47c11854e77892336c22ac1d714fec/includes/preprocess.page.inc#L12-L17
https://github.com/openfed/kiso/blob/4035ba060c47c11854e77892336c22ac1d714fec/includes/preprocess.utils.inc#L22-L34

Could you please provide me with code example to implement in the `twig` template?

**Comment by lramarojaona** [comment]
@smillart ,
I implemented the suggested way and removed related PHP code.

I did not add the `strip_tags`, I guess we'll need to add it somehow to prevent breaking existing sites.

So this patch is WIP.

[kiso-64.patch](https://github.com/openfed/kiso/files/14693748/kiso-64.patch)

**Comment by lramarojaona** [comment]
Ther is a small typo in previous patch with `page_foote` which should be `page_footer`.

Here's the updated patch.

[kiso-64-2.patch](https://github.com/openfed/kiso/files/14701631/kiso-64-2.patch)

**Comment by GyD** [comment]
@lramarojaona I confirm you need to add `|striptags('<drupal-render-placeholder><img><video><[...]>')|trim` in order to have it work. Otherwise you end up with empty region displayed.

Maybe using https://www.drupal.org/project/twig_real_content could be a good idea if bosa agree!?

**Comment by lramarojaona** [comment]
Ok, maybe we should  create custom twig functions or filters for that: https://drupaljournal.com/article/drupal/creating-custom-twig-functions-and-filters-drupal

**Comment by rutiolma** [comment]
I don't fully agree with the solution. Removing this twig function will require an update to hundreds of sites, which is not really super simple.
Why can't we keep the old function and adapt it to use real content?! Wouldn't that be more efficient?

**Comment by lramarojaona** [comment]
@rutiolma , good point, but it should be somehow marked as deprecated.

**Comment by rutiolma** [comment]
> @rutiolma , good point, but it should be somehow marked as deprecated.

IMHO we could keep the "has_region" function in Kiso and use it as we've been doing. It's way more clean to check for an empty region. 
This
`{% if has_tools %}`
vs
`{% if page.tools|render is real_content %}`

If we mark it as deprecated, we should remove it for version 4.0.x and not before otherwise all existing projects will have to change their themes due to a minor release.

**Comment by jclemmenb4y** [comment]
I seems to be a safer approach for now.

I know I'm overriding the has_region function in almost all my themes as it didn't really work (especially for regions with content such as facets).

But does this approach solve anything performance wise? As this was the initial concern. @GyD what do you think?

**Comment by GyD** [comment]
We should ne able to create a has_{region} using php  classes from twig_real_content within _kiso_has_region function. I’ll investigate that.

**Comment by ninjadrupal** [comment]
> To give more detail <?php render function do not return the final output. That could lead to false result, example: when a drupal placeholder return nothing.
> 
> This can be tested with facets module and facet option that do not render the facets when the facet source is not rendered.
> 
> Laurent solution is the one we put on werkenvoor but may not be the best since this issue need investigation.
> 
> Example, with facet we currently have this output in php on page where facet are not rendered:
> 
> ```
> '  <drupal-render-placeholder callback="Drupal\\block\\BlockViewBuilder::lazyBuilder" arguments="0=category&amp;1=full&amp;2" token="3H-ATSLp_IKUKYnhOjRX3yjcYQjgLT6WOepB79hscJI"></drupal-render-placeholder>
> '
> ```
> 
> But when you render in twig it return
> 
> ```
> ''
> ```
> 
> Please note that solution implemented in Kiso also render region and their content multiples times (at least twice), that could lead to performances issues.

i have the same issue in one of the sites :/  after the upgrade to openfed  12
