### ISSUE TITLE
site_name var is not defined/preprocessed

### ISSUE THREAD

**Issue by rutiolma** [openfed/kiso#66]
We noticed that when using block--system-branding-block.html.twig the variable site_name is empty and we had to use a preprocess like:
```
/**
 * Implements hook_preprocess_block().
 */
function eu_disability_card_preprocess_block(&$variables) {

  // Load the site name out of configuration.
  $config = \Drupal::config('system.site');
  $variables['site_name'] = $config->get('name');

}
```
Additionally, I see that site_name is also used on other twigs so we may need more preprocesses.

**Comment by smillart** [comment]
The variable `site_name` is not really empty. This just means that the _"Site name"_ checkbox _(from the "Toggle Branding Elements" panel)_ is unchecked in the "Site branding" configure block page.

**Comment by rutiolma** [comment]
Thanks @smillart, that's clear.
