### ISSUE TITLE
Alternative way to display title in views-view.html.twig

### ISSUE THREAD

**Issue by kzenmatthias** [openfed/kiso#67]
I didn't know that in some cases you display the title in views-view.html.twig by using `{{ view.title }}`
For other people in the future, it may be useful to know that this is a possibility.

Can we add this comment above the following code?
```
  // If title is not displayed, use {{ view.title }}
  {{ title_prefix }}
  {{ title }}
  {{ title_suffix }}
```

**Comment by smillart** [comment]
@kzenmatthias, the case you have with your project is to specific to be mentioned in the Kiso's theme override for a main view template.

The following `{{ title }}` variable _(you mentioned in the issue description)_ which stands in the default `views-view.html.twig` template is only used when displaying in the admin preview:
https://github.com/openfed/kiso/blob/32b2fc2a823630a719cc5ffc2bd34aecf681be1a/templates/views/views-view.html.twig#L38-L40

Most of the time the view title stands within the `block.html.twig` template when the view is displayed as "Block":
https://github.com/openfed/kiso/blob/32b2fc2a823630a719cc5ffc2bd34aecf681be1a/templates/block/block.html.twig#L26-L30
And within the `page-title.html.twig` template when the view is displayed as "Page":
https://github.com/openfed/kiso/blob/32b2fc2a823630a719cc5ffc2bd34aecf681be1a/templates/content/page-title.html.twig#L13-L17

**Comment by smillart** [comment]
@kzenmatthias, If you agree, I gonna cancel this issue as your request is a too specific case to be added in the Kiso's theme override for the main view template.
