### ISSUE TITLE
Make it ready to Drupal 10

### ISSUE THREAD

**Issue by rutiolma** [openfed/kiso#68]
From what I could acknowledge there're no major differences between D9 and D10 themes so Kiso should work well on D10 sites but it has to, at least, allow D10 at kiso.info.yml

Please double check.

**Comment by kzenmatthias** [comment]
Some functions were Deprecated in Drupal 9 and removed in Drupal 10.
I replaced these functions.

**Comment by lramarojaona** [comment]
I just made a patch and saw this issue.
[kiso-68_d10-readiness.patch](https://github.com/openfed/kiso/files/10559307/kiso-68_d10-readiness.patch)

Almost the same.
FYI, D8.8 minimum version is required, but I doubt we will still have such old sites.
