### ISSUE TITLE
Security/performance issue

### ISSUE THREAD

**Issue by GyD** [openfed/kiso#79]
In kiso.theme the following code is used:

```php
/**
 * Declare various [pre]process/hook functions.
 *
 * All [pre]process/hook functions must live (via include) inside this
 * file so they are properly detected when drupal_alter() is invoked.
 */
if (is_dir(__DIR__ . '/' . INCLUDES_FOLDER)) {
  $files = scandir(__DIR__ . '/' . INCLUDES_FOLDER);
  if (!empty($files)) {
    foreach ($files as $file) {
      kiso_include('kiso', INCLUDES_FOLDER . '/' . $file);
    }
  }
}
```
Scandir is used, it could lead to security issues where injected files in the include folders could be executed.
Scandir can also be disabled for security reasons on some hosting services .

Using theme like other themes (ex: GIN does) do not solve thoses issues (possible injected files can still be executed, glob can be disabled by hosting service)
```php
foreach (glob(\Drupal::service('extension.list.theme')->getPath('kiso') . '/includes/*.inc') as $file) {
  include $file;
}
```

In addition scanning a folder for files is a bit "heavy". I think the scan result will not be stored in PHP JIT so it will be executed each time. 

Since there is not a lot of files to be included code can be replaced by 
```php
include_once "includes/alter.page-attachments.inc";
include_once "includes/alter.theme-suggestions.inc";
include_once "includes/preprocess.block.inc";
include_once "includes/preprocess.html.inc";
include_once "includes/preprocess.inc";
include_once "includes/preprocess.links.inc";
include_once "includes/preprocess.maintenance-page.inc";
include_once "includes/preprocess.menu-local-task.inc";
include_once "includes/preprocess.page.inc";
include_once "includes/preprocess.utils.inc";
```

**Comment by smillart** [comment]
Thanks @GyD for reporting this... I think using `include_once` should be a better alternative... Will do!
