### ISSUE TITLE
Deprecated function: preg_replace

### ISSUE THREAD

**Issue by rutiolma** [openfed/kiso#80]
When using PHP8.1 we get the following error:

`Deprecated function: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in _kiso_has_region() (line 24 of themes/contrib/kiso/includes/preprocess.utils.inc).`

Can you update it to make sure this is compatible with current PHP versions?

**Comment by smillart** [comment]
@rutiolma Do you know how can I fix this problem? What changes can I make to the existing code?
