### ISSUE TITLE
Improve theming possibilities for block_content entities

### ISSUE THREAD

**Issue by lramarojaona** [openfed/kiso#83]
It seems that when using `block_content` entities there's a poor support for theming.

These 2 functions will add classes and theme suggestions based on the block type:
```php
/**
 * Implements template_preprocess_block().
 */
function kiso_preprocess_block(&$variables) {
  // Add classes for block_content entities, based on block type.
  if ($variables['base_plugin_id'] == 'block_content' && !empty($variables['content']['#block_content'])) {
    /** @var \Drupal\block_content\BlockContentInterface $block_content */
    $block_content = $variables['content']['#block_content'];
    $variables['attributes']['class'][] = 'block--block_content--' . $block_content->bundle();
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function kiso_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  // Add theme suggestions for block_content entities, based on block type.
  if ($hook == 'block'
    && $variables['elements']['#base_plugin_id'] == 'block_content'
    && !empty($variables['elements']['content']['#block_content'])) {
    /** @var \Drupal\block_content\BlockContentInterface $block_content */
    $block_content = $variables['elements']['content']['#block_content'];
    $suggestions[] = $hook . '__block_content__' . $block_content->bundle();
  }
}
```
![2023-06-22 16_47_09-Homepage _ Data gov be — Mozilla Firefox](https://github.com/openfed/kiso/assets/5821299/1804be25-42f4-41ea-be26-9a486591ec73)

Related d.o issue: https://www.drupal.org/project/drupal/issues/1896098

**Comment by lramarojaona** [comment]
I _think_ underscores in the class name might probably need to be replaced by hypens `-` to be consistent with all other classes.

**Comment by smillart** [comment]
Regarding utility classes to be used within the `block.html.twig` template, both the `configuration.provider` and the `derivative_plugin_id` _Twig_ variables are used to print the generated module (Provider) and a related useful class. These variables pass through the `clean_class` filter in the _Twig_ template to prepare a string for use as a valid HTML class name (replacing `_` by `-`) [ see [Html::getClass()](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Html.php/function/Html%3A%3AgetClass/9) ].

**We need to update the following source code:**
https://github.com/openfed/kiso/blob/32b2fc2a823630a719cc5ffc2bd34aecf681be1a/includes/preprocess.block.inc#L21-L24

**... using the following one (based on your code @lramarojaona):**

```php
// "Custom block" provider.
case 'block_content':
  if (!empty($variables['content']['#block_content'])) {
    /** @var \Drupal\block_content\BlockContentInterface $block_content */
    $block_content = $variables['content']['#block_content'];
    $view_mode = strtr($elements['#configuration']['view_mode'], '.', '_');
    $variables['derivative_plugin_id'] = ($view_mode !== 'default') ? $block_content->bundle() . '__' . $view_mode : $block_content->bundle();
  }
  else  {
    $variables['derivative_plugin_id'] = $elements['#derivative_plugin_id'];
  }
  break;
```
I just added the `$view_mode` variable when block types are using specific view mode displays other than the "default" one.
