### ISSUE TITLE
Big messages not correctly displayed in Drupal messages

### ISSUE THREAD

**Issue by lramarojaona** [openfed/kiso#98]
When debugging with devel and symfony var_dumper, we sometimes need to display large arrays or objects.

It seems the message area has a fixed height, which makes almost impossible to read those dumps:

![2023-08-25 15_55_01-Prothesists _ FEDRIS — Mozilla Firefox](https://github.com/openfed/kiso/assets/5821299/be64e0a9-4580-4e3a-9f7f-efe05486e594)

The message area should adapt to its content.

**Comment by smillart** [comment]
@lramarojaona Is using the `<pre>` element height the issue you have?

**Comment by lramarojaona** [comment]
@smillart , yes indeed, see my screenshot:
![2024-01-30 10_04_49-Suche _ BOSA — Mozilla Firefox](https://github.com/openfed/kiso/assets/5821299/4f89b29d-5491-4ae7-a30f-59149323e53a)
