### ISSUE TITLE
Html unique IDs

### ISSUE THREAD

**Issue by lramarojaona** [openfed/kiso#99]
In most of our projects we need to add

```php
function THEME_form_alter(&$form, &$form_state, $form_id) {
  $form['#id'] = Html::getUniqueId($form['#id']);
}
```

To make sure we have unique IDs (like search box placed twice on the page).

I think it would be a nice addition to kiso.

To be checked: do we also need this with `hook_preprocess_block()`?

**Comment by smillart** [comment]
@lramarojaona Is the code you provided above is still up to date and compatible with D10?

**Comment by lramarojaona** [comment]
@smillart ,
Yes it should be still relevant and compatible.

**Comment by neyensp** [comment]
Here the patch to rollback the alter [kiso-remove-form-alter-to-make-id-unique-F2W-382.patch](https://github.com/user-attachments/files/22022202/kiso-remove-form-alter-to-make-id-unique-F2W-382.patch)
